name: Test GT7 Telemetry Agent

on:
  pull_request:
    branches: [ main ]

jobs:  
  test:
    name: Run Tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest nuitka
      - name: Run tests
        run: |
          pytest tests
