name: PR GT7 agent Test and Build

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Run Tests (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest nuitka
      - name: Run tests
        run: |
          pytest tests
  
  build-linux:
    needs: [test]
    name: Build Linux Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build Linux Executable
        run: |
          python -m nuitka --standalone --assume-yes-for-downloads --onefile --follow-imports --output-filename=gt7_telemetry_agent-linux.bin gt7/gt7_telemetry_agent.py

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gt7_telemetry_agent-linux-${{ github.run_number }}
          path: gt7_telemetry_agent-linux.bin

  build-windows:
    name: Build Windows Release
    needs: [test]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build Windows Executable
        run: |
          python -m nuitka --standalone --assume-yes-for-downloads --windows-company-name="GT Telemetry" --windows-product-name="GT7TelemetryAgent" --windows-product-version=${{ github.run_number }} --follow-imports --remove-output gt7/gt7_telemetry_agent.py

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gt7_telemetry_agent-windows-${{ github.run_number }}
          path: gt7_telemetry_agent.dist/*

  build-macos:
    name: Build macOS Release
    needs: [test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Nuitka
        run: pip install nuitka
      
      - name: Build macOS Executable
        run: |
          python -m nuitka --standalone --assume-yes-for-downloads --onefile --follow-imports --output-filename=gt7_telemetry_agent-macos.bin gt7/gt7_telemetry_agent.py

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: gt7_telemetry_agent-macos-${{ github.run_number }}
          path: gt7_telemetry_agent-macos.bin
